### ISSUE TITLE
Dashboard/Home view

### ISSUE THREAD

**Issue by justdodo27** [justdodo27/gymshare#104]
- [x] Navigation rails / Tabs
    - [x] Workouts (list)
        - [x] Search bar with filters and ordering
        - [x] Pagination system
        - [x] #100 
    - [x] Exercises (list)
        - [x] Search bar with filters and ordering
        - [x] Pagination system
        - [x] #102
